# Generated by Django 4.0.3 on 2022-04-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=100)),
                ('ecoscore', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=250)),
                ('linkoff', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('energy', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
                ('sugar', models.FloatField()),
                ('saturedfat', models.FloatField()),
                ('fat', models.FloatField()),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutriment', serialize=False, to='openfoodfacts.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='openfoodfacts.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='openfoodfacts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
