# Generated by Django 4.0.3 on 2022-03-23 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.FloatField(null=True)),
                ('salt', models.FloatField(null=True)),
                ('sugar', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=100)),
                ('ecoscore', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=250)),
                ('nutriment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutriment', to='openfoodfacts.nutriment')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='openfoodfacts.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='openfoodfacts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
