# Generated by Django 4.0.3 on 2022-03-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0003_alter_product_nutriment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutriment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutriment', to='openfoodfacts.nutriment'),
        ),
    ]
